import { auth, validateRequest } from '@/app/middlewares';
import { Role } from '@prisma/client';
import { Router } from 'express';
import * as controller from './project.controller';
import * as validation from './project.validation';
import { fileUploader } from '@/shared/helpers';
const router = Router();
router.post('/', auth(Role.ADMIN), fileUploader.upload.single('file'), validateRequest(validation.projectSchema), controller.createProject);
router.get('/', controller.getAllProject);
router.get('/:id', controller.getSingleProject);
router.patch('/update/:id', auth(Role.ADMIN), controller.updateProject);
router.delete('/delete/:id', auth(Role.ADMIN), controller.deleteProject);
export default router;
